on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y nettle-dev libssl-dev clang
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y nettle-dev libssl-dev clang
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install nettle
        run: sudo apt-get install -y nettle-dev libssl-dev clang
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  verify-commit:
    name: Verify Commit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: git verify-commit HEAD
